#ifndef ZG_SYS_CONFIG_H
#define ZG_SYS_CONFIG_H


#ifdef CONFIG_APPCONFIG_SURPLIFE_CMD
#define APPCONFIG_SURPLIFE_CMD
#endif

#ifdef CONFIG_APPCONFIG_MAGICHOME_CMD
#define APPCONFIG_MAGICHOME_CMD
#endif

#define ZG_TCP_SERVER_TASK_PRIO            PORT_CONFIG_TCP_SERVER_TASK_PRIO
#ifdef CONFIG_TCPS_TASK_STACK_SIZE
#define ZG_TCP_SERVER_TASK_STACK_SZ        CONFIG_TCPS_TASK_STACK_SIZE
#else
#define ZG_TCP_SERVER_TASK_STACK_SZ        (1024)
#endif

#define ZG_TCP_CLIENT_TASK_PRIO            PORT_CONFIG_TCP_CLIENT_TASK_PRIO
#ifdef CONFIG_TCPC_TASK_STACK_SIZE
#define ZG_TCP_CLIENT_TASK_STACK_SZ        CONFIG_TCPC_TASK_STACK_SIZE
#else
#define ZG_TCP_CLIENT_TASK_STACK_SZ        (1024)
#endif

#define ZG_TCP_CLIENT_SEND_TASK_PRIO       PORT_CONFIG_TCP_CLIENT_SEND_TASK_PRIO
#ifdef CONFIG_TCPC_SEND_TASK_STACK_SIZE
#define ZG_TCP_CLIENT_SEND_TASK_STACK_SZ   CONFIG_TCPC_SEND_TASK_STACK_SIZE
#else
#define ZG_TCP_CLIENT_SEND_TASK_STACK_SZ   (700)
#endif

#define ZG_UDP_SERVER_TASK_PRIO            PORT_CONFIG_UDP_SERVER_TASK_PRIO
#ifdef CONFIG_UDP_TASK_STACK_SIZE
#define ZG_UDP_SERVRE_TASK_STACK_SZ        CONFIG_UDP_TASK_STACK_SIZE
#else
#define ZG_UDP_SERVRE_TASK_STACK_SZ        (512)
#endif

#define ZG_FOTA_TASK_PRIO                  PORT_CONFIG_FOTA_TASK_PRIO
#ifdef CONFIG_FOTA_TASK_STACK_SIZE
#define ZG_FOTA_TASK_STACK_SZ              CONFIG_FOTA_TASK_STACK_SIZE
#else
#define ZG_FOTA_TASK_STACK_SZ              (1024)
#endif

#define ZG_EVENT_LOOP_TASK_PRIO            PORT_CONFIG_ZG_EVENT_LOOP_TASK_PRIO
#define ZG_EVENT_LOOP_TASK_STACK_SZ        (768)

#define ZG_WATCHDOG_TASK_PRIO              PORT_CONFIG_ZG_WATCHDOG_TASK_PRIO
#ifdef CONFIG_WDG_TASK_STACK_SIZE
#define ZG_WATCHDOG_TASK_STACK_SZ          CONFIG_WDG_TASK_STACK_SIZE
#else
#define ZG_WATCHDOG_TASK_STACK_SZ          (256)
#endif

#define ZG_KV_TASK_PRIO                    PORT_CONFIG_KV_TASK_PRIO

#define ZG_BT_REMOTE_EVENT_TASK_PRIO       PORT_CONFIG_BT_REMOTE_EVENT_TASK_PRIO 
#ifdef  CONFIG_BT_RMT_TASK_STACK_SIZE
#define ZG_BT_REMOTE_EVENT_STACK_SZ        CONFIG_BT_RMT_TASK_STACK_SIZE
#else
#define ZG_BT_REMOTE_EVENT_STACK_SZ        (768)
#endif

#define CONFIG_ZG_DATA_HANDLE_TASK_STACK_SIZE  1024
#define CONFIG_BLE_PRO_HANDLE_TASK_STACK_SIZE  1024


#define ZG_system_time()                PORT_CONFIG_SYSTEM_TIME  
#define ZG_AES_FLASH_ADDR               PROT_CONFIG_KEY_FLASH_ADDR
#define ZG_AES_KEY_OFFSET               PROT_CONFIG_KEY_FLASH_OFFSET
#define ZG_CIPHERTEXT_ADDR              PORT_CONFIG_CIPHERTEXT_FLASH_ADDR 
#define ZG_IIC_ADDR                     PORT_CONFIG_IIC_FLASH_ADDR 
#define ZG_USER_DATA_FLASH_ADDR         PORT_CONFIG_USER_DATA_FLASH_ADDR
#define ZG_USER_DATA_SIZE               PORT_CONFIG_USER_DATA_SIZE
#define ZG_OTA_IMAGE_NAME               PORT_CONFIG_OTA_IMAGE_NAME


#define ZG_RED_PWM_CH    PORT_CONFIG_PWM_RED_CHANNEL
#define ZG_GREEN_PWM_CH  PORT_CONFIG_PWM_GREEN_CHANNEL
#define ZG_BLUE_PWM_CH   PORT_CONFIG_PWM_BLUE_CHANNEL
#define ZG_WARM_PWM_CH   PORT_CONFIG_PWM_WARM_CHANNEL
#define ZG_COLD_PWM_CH   PORT_CONFIG_PWM_COLD_CHANNEL
#endif

